spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
#  jpa:
#    hibernate:
#      ddl-auto: none
#    properties:
#      hibernate:
#        show_sql: false
  sql:
    init:
      mode: always  # Options: always, embedded, never
#  batch:
#    jdbc:
#      initialize-schema: always